"""empty message

Revision ID: ee665c7b9095
Revises: 39200ec395a7
Create Date: 2019-02-15 17:10:59.300000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee665c7b9095'
down_revision = '39200ec395a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uuid_UNIQUE', table_name='user')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('uuid_UNIQUE', 'user', ['uuid'], unique=True)
    # ### end Alembic commands ###
